### ISSUE TITLE
insufficient group privileges / group_id issue

### ISSUE THREAD

**Issue by JadedEvan** [adamgriffiths/ag-auth#1]
Noticed a bug in the libraries/Auth.php file, near line 82:

Reads:
$user_level = $this->CI->session->userdata('group');

When it should be:
$user_level = $this->CI->session->userdata('group_id');

As in the login() function in the same file you set the session variable as 'group_id', not 'group'

**Comment by JadedEvan** [comment]
Similarly, I added a redirect based on the user's group settings at the end of the login() function. Again there is trouble because of the group/group_id issue. Around line 143:
    $auth_type => $username,
    'username' => $row['username'],
    'user_id' => $row['id'],
    'group_id' => $row['group_id'],
    'logged_in' => TRUE
    );

Nowhere in that block is the 'group' being set. It'd be nice to access that instead of passing around the group_id.

**Comment by adamgriffiths** [comment]
I have fixed this issue in the latest commit to the repo. The correct reference for the group ID is 'group_id' not 'group'.

Hopefully this clears things up.

If you'd like to double check this in the repo I can close this issue then.

Thanks.
