### ISSUE TITLE
Not working under CI 2.02

### ISSUE THREAD

**Issue by designermonkey** [adamgriffiths/ag-auth#11]
I can't get this to work at all, I keep getting:

`Fatal error: Class 'Application' not found in /Users/designermonkey/Projects/Chameleon/codeigniter/httpdocs/application/controllers/admin/admin.php on line 4`

**Comment by adamgriffiths** [comment]
You need to extend CI_Controller in the MY_Controller.php library file…also need to move it to app/core/ I'll get on this as soon as I move my workflow back to git from mercurial.

**Comment by designermonkey** [comment]
Thanks for your reply Adam.

I'm quite new to Codeigniter...

**Comment by adamgriffiths** [comment]
Fixed this in v2.0.0.

**Comment by designermonkey** [comment]
Awesome, will play with this tmora.
