### ISSUE TITLE
Auth/Users

### ISSUE THREAD

**Issue by jeffreylo** [adamgriffiths/ag-auth#14]
Codeigniter throws a usermodel not found error, but looking through the repo, I realize that it's not included with the package. Is this intentional?

**Comment by adamgriffiths** [comment]
Very good point. I have now removed the need for a usermodel.php model file, you can find this fix in the master branch. This will be rolled into the next release along with any other possible future bugs.

Thanks.

**Comment by jeffreylo** [comment]
Any idea when the next release might be? If not, I'll probably move to write my own model for the users.

There were a few other bugs with the package that I'll send along in a pull request.

**Comment by adamgriffiths** [comment]
Everything in master is a stable release with some added extras. I just don't want to tag a new release with one or two additions to it. The usermodel is now not needed, as it only had a delete function in anyways, so now the controller uses the Database library.

**Comment by jeffreylo** [comment]
I see. As it is, though, the users controller still makes reference to a non-existant user model.

From the manage method in the users controller:

``` php
$data = $this->users->users(); // Grab an array of users from the database
```

Sorry about all the posting; I just want to understand if the library currently supports some basic user management or not.

Thanks for all your work!

**Comment by adamgriffiths** [comment]
I've issued another fix…I must have missed the users list the first time around. The library does support user management, I had simply missed a few things whilst transitioning. It should all be fine now.

**Comment by jeffreylo** [comment]
Thanks for the quick response, Adam!
