### ISSUE TITLE
infinite redirecting loop

### ISSUE THREAD

**Issue by bluevibe** [adamgriffiths/ag-auth#2]
The value of config['auth_login'] is used for both failed and successful logins.

So, if you try to access some controller without being authenticated for it , you're redirected to config['auth_login'], but naturally, you're not authenticated for that either, so it redirects you .. to config['auth_login']. and so forth.

**Comment by adamgriffiths** [comment]
Thanks for letting me know. I'm fixing this right now.

**Comment by adamgriffiths** [comment]
Fixed redirect error on unsuccessful login closed by 5d6b8e817981961743d1da1358f024b698ab2acd
