### ISSUE TITLE
why meta redirect?

### ISSUE THREAD

**Issue by bluevibe** [adamgriffiths/ag-auth#3]
on line 96 it uses a meta refresh for the redirect. unless this is very clever for some reason I suggest it changed into a normal header location redirect.

**Comment by adamgriffiths** [comment]
Is there a specific problem with using the helper redirect() function?

I have no qualms with changing it I would just like to know the benefits.

Thanks.

**Comment by bluevibe** [comment]
Hi Adam

I think it could be that this is not a big deal, that's why this is more of a question.

The only issue I've had with it is that it didn't redirect me at all (becase I had disabled meta redirects in my browser). But I'm pretty sure almost no one has that. 

With a auth solution I feel that I would take that option away from the user, "if you're not authenticated, get out", and be sure that they are infact redirected, which they would be in all cases as far as I know with a location redirect (default).

But maybe you had some good reasons for going for the refresh redirect, if so please share :)
