### ISSUE TITLE
Expired Sessions

### ISSUE THREAD

**Issue by xdeskproductions** [adamgriffiths/ag-auth#5]
I frequently leave my computer on and happened to leave Firefox open with myself at the login screen for a very long time, so when I came back to working on things I put in the wrong information to begin with but when I did I got an error:

<pre>
A PHP Error was encountered
Severity: Notice
Message: Undefined index: login_attempts
Filename: libraries/Auth.php
Line Number: 325
</pre>

As best I could tell, this was due to not checking if the session existed or something. Anyways I thought I would share it.

**Comment by adamgriffiths** [comment]
What version of The Authentication Library are you using?

This issue was fixed a few revisions ago.

Thanks.

**Comment by xdeskproductions** [comment]
First time downloading it a few days ago.

**Comment by adamgriffiths** [comment]
I found the problem. I'll work out the best way to fix it and commit soon.

Thanks.

**Comment by kon** [comment]
Any chance for a fix?

**Comment by adamgriffiths** [comment]
Is this still an issue in v2.0.1?

**Comment by adamgriffiths** [comment]
This should be fixed in the latest 2.0.2 version.
