### ISSUE TITLE
Offline random.org PHP Notices

### ISSUE THREAD

**Issue by xdeskproductions** [adamgriffiths/ag-auth#6]
Other than the obvious not being able to get the random url, in the offline processing your line 361 has the following code which in itself produces an error.

[code]          $token = ”;    [/code]

I fixed the issue using '' instead of the special character quotation.

Only reason I noticed the error is I am driving to Anaheim, CA for Blizzcon and working in the backseat off an AT&T Wireless card. Should produce similar results by _gasp_ unplugging.

**Comment by adamgriffiths** [comment]
Fixed in 2.0.0.
